### ISSUE TITLE
Can't build v0.5.0

### ISSUE THREAD

**Issue by crispy-caesus** [heather7283/pipemixer#33]
System:
OS: Chimera Linux
libc: musl
compiler: llvm/clang

`meson compile -C build` output:
```
INFO: autodetecting backend as ninja
INFO: calculating backend command to run: /usr/bin/ninja -C /home/crispy/Documents/github/pipemixer/build
ninja: Entering directory `/home/crispy/Documents/github/pipemixer/build'
[12/22] Compiling C object pipemixer.p/src_collections_dict.c.o
FAILED: [code=1] pipemixer.p/src_collections_dict.c.o 
cc -Ipipemixer.p -I. -I.. -I../src -I/usr/include/pipewire-0.3 -I/usr/include/spa-0.2 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -O0 -g -Wno-pedantic -Wno-unused-value -Wno-unused-parameter '-DPIPEMIXER_GIT_TAG="v0.5.0"' '-DPIPEMIXER_GIT_BRANCH="master"' '-DPIPEMIXER_VERSION="0.5.0"' -D_REENTRANT -fno-strict-aliasing -fno-strict-overflow -DNCURSES_WIDECHAR -MD -MQ pipemixer.p/src_collections_dict.c.o -MF pipemixer.p/src_collections_dict.c.o.d -o pipemixer.p/src_collections_dict.c.o -c ../src/collections/dict.c
../src/collections/dict.c:38:5: error: unknown type name 'ssize_t'; did you mean 'size_t'?
   38 |     ssize_t l = 0, r = dict->size - 1;
      |     ^~~~~~~
      |     size_t
/usr/include/bits/alltypes.h:50:24: note: 'size_t' declared here
   50 | typedef unsigned _Addr size_t;
      |                        ^
../src/collections/dict.c:41:15: error: unknown type name 'ssize_t'; did you mean 'size_t'?
   41 |         const ssize_t m = l + (r - l) / 2;
      |               ^~~~~~~
      |               size_t
/usr/include/bits/alltypes.h:50:24: note: 'size_t' declared here
   50 | typedef unsigned _Addr size_t;
      |                        ^
2 errors generated.
[21/22] Compiling C object pipemixer.p/src_pw_node.c.o
ninja: build stopped: subcommand failed.
```

I'm rather certain it worked on 0.4.3, I'm not very versed in C, but it seems that ssize thing is something that can't be found on my system. I'm not sure if that's a dependency thing, compiler extention or something else.

**Comment by heather7283** [comment]
Can you try building from latest commit?

**Comment by crispy-caesus** [comment]
Ahh yes, now it builds again :D. Hope it isn't too much of an inconvenience. Thank you!
